### ISSUE TITLE
[Checklist] Cycle 2.1

### ISSUE THREAD

**Issue by mameaw14** [kritsana-chaikaew/human-for-hire#17]
ทำเสร็จวันจันทร์หน้าหน้า
## งานค้าง
- [x]  แก้ระบบ password ให้เหมือนกัน @natachit @kaisukez 
- [x] แก้ ระยะห่างบรรทัด หน้า Edit Profile @mameaw14
- [x] ซ่อมเว็บไม่ให้บึ้ม @kritsana-chaikaew 
- [x] หน้า Edit Profile @kaisukez @natachit 
- [x] ดึงชื่อ user มาตั้งโพส (ยกเลิกช่องใส่ชื่อในหน้า Post) @kanoonsantikul 
- [x] Edit Post @kanoonsantikul 

## Filter
- sarach olan
- @...... @XrosIsorX 
- [x] Filter อายุ เพศ ช่วงวันที่ที่ว่าง 

## Tag 
- eye cello niti 
- @moeyeo @celloAlbatross @kanoonsantikul 
- [x] ออกแบบระบบ Tag 
- [x] implement ระบบ
- [x] มีหน้ารวมแท็ก

## Checkout & Confirm 
- graph tawan mameaw
- @kaisukez @natachit @mameaw14
- [x] หน้ากดซื้อ 
- [x] หน้าจ่ายตัง
- [x] หน้า Manage งาน ของ Buyer
- [x] หน้ากดยืนยันงานเสร็จของ Buyer
