### ISSUE TITLE
[Checklist] Cycle 1

### ISSUE THREAD

**Issue by mameaw14** [kritsana-chaikaew/human-for-hire#6]
# Checklist
### แม้ก เชลโล่ กราฟ
- [x] Register สมัครสมาชิกได้
- [x] Login หน้าล๊อกอิน ล๊อกอินได้
- [x] Logout สามารถล๊อกเอาท์ได้

### อาย ตะวัน มะเหมี่ยว
- [x] Profile สามารถดูโปรไฟล์ตัวเองได้
- [x] Edit Progile สามารถแก้ไขข้อมูลของตัวเองได้

### เจเล็ก ขนุน แบงค์
- [x] Post เมื่อเข้าสู่ระบบ สามารถโพสได้ 
- [ ] Edit Post สามารถแก้ไขโพสได้
- [x]  หน้าแรก

### เจเฮด มะเหมี่ยว
- [x] Bootstrap 4 ครอบ ui ทั้งหมด

**Comment by mameaw14** [comment]
ยกยอดงานค้างไปอยู่ #17 แล้ว
